run:
  tests: true

linters:
  disable-all: false
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomnd
    - lll
    - nakedret
    - wsl
    - bodyclose

issues:
  exclude:
    - Using the variable on range scope `tc` in function literal
    - Using a reference for the variable on range scope `req`
